/**
 * @file iconMap.ts
 * @description 统一的图标映射配置 - 与后台 admin/src/config/icons.tsx 保持一致
 * @copyright 版权所有 (c) 2025 UIED技术团队
 * @website https://fsuied.com
 * @license MIT
 */

import { 
  DesignIcons, 
  IconTool, 
  IconTools,
  IconDigital, 
  IconSystem, 
  IconDesignTeam, 
  IconCarUI,
  IconGameUI,
  IconMetaverse,
  IconAIDesign,
  IconOtherContent,
  IconEducation,
  IconLearning,
  IconInspiration,
  IconMaterial,
  IconFont,
  IconColor,
  IconPrint,
  IconGraphic,
  IconBrand,
  IconPhoto,
  IconArt,
  IconStore,
  IconCamera,
  IconLayout,
  IconMarketing,
  IconPlatform,
  IconLiveStreaming,
  IconBanner,
  IconPackage,
  IconIllustration,
  IconComponents,
  IconMockup,
  IconPalette,
  IconCAD,
  IconFurniture,
  IconTexture,
  IconLighting,
  IconProject,
  IconVR,
  Icon3D
} from '../components/UI/Icons';
import { IconComponent } from '../types/icon';

/**
 * 统一的图标映射表
 * key 与后台 admin/src/config/icons.tsx 中的 availableIcons 保持一致
 */
export const iconMap: Record<string, IconComponent> = {
  // ============ 设计相关 ============
  'inspiration': IconInspiration,
  'ui': DesignIcons.UI,
  'graphic': IconGraphic,
  'template': DesignIcons.Template,
  'material': IconMaterial,
  'icons': DesignIcons.Icons,
  'color': IconColor,
  'font': IconFont,
  'brand': IconBrand,
  'prototype': DesignIcons.Prototype,
  'kit': DesignIcons.Kit,
  'animation': DesignIcons.Animation,
  '3d': Icon3D,
  'print': IconPrint,
  'art': IconArt,
  'figma': DesignIcons.Figma,
  'illustration': IconIllustration,
  'components': IconComponents,
  'mockup': IconMockup,
  'palette': IconPalette,
  
  // ============ 媒体相关 ============
  'image': DesignIcons.Image,
  'photo': IconPhoto,
  'video': DesignIcons.Video,
  'audio': DesignIcons.Audio,
  'camera': IconCamera,
  
  // ============ 技术相关 ============
  'ai': DesignIcons.AI,
  'code': DesignIcons.Code,
  'developer': DesignIcons.Developer,
  'web': DesignIcons.Web,
  'mobile': DesignIcons.Mobile,
  'plugin': DesignIcons.Plugin,
  'data': DesignIcons.Data,
  'analytics': DesignIcons.Analytics,
  'visualization': DesignIcons.Visualization || IconDigital,
  'gameui': IconGameUI,
  'metaverse': IconMetaverse,
  'digital': IconDigital,
  'system': IconSystem,
  
  // ============ 商业相关 ============
  'ecommerce': DesignIcons.Ecommerce,
  'store': IconStore,
  'marketing': IconMarketing,
  'platform': IconPlatform,
  'livestreaming': IconLiveStreaming,
  'banner': IconBanner,
  'package': IconPackage,
  
  // ============ 电商相关 ============
  'layout': IconLayout,
  'specs': DesignIcons.Specs,
  
  // ============ 室内设计 ============
  'cad': IconCAD,
  'furniture': IconFurniture,
  'texture': IconTexture,
  'lighting': IconLighting,
  'project': IconProject,
  'vr': IconVR,
  
  // ============ 通用图标 ============
  'tool': IconTool,
  'tools': IconTools,
  'tutorial': DesignIcons.Tutorial,
  'learn': DesignIcons.Learn,
  'blog': DesignIcons.Blog,
  'community': DesignIcons.Community,
  'book': DesignIcons.Book,
  'education': IconEducation,
  'resource': DesignIcons.Resource,
  'carui': IconCarUI,
  'designteam': IconDesignTeam,
  'aidesign': IconAIDesign,
  'othercontent': IconOtherContent,
  'learning': IconLearning,
  
  // ============ 兼容性映射（大写、驼峰等） ============
  'Inspiration': IconInspiration,
  'UI': DesignIcons.UI,
  'Graphic': IconGraphic,
  'Template': DesignIcons.Template,
  'Material': IconMaterial,
  'Icons': DesignIcons.Icons,
  'Color': IconColor,
  'Font': IconFont,
  'Brand': IconBrand,
  'Prototype': DesignIcons.Prototype,
  'Kit': DesignIcons.Kit,
  'Animation': DesignIcons.Animation,
  '3D': Icon3D,
  'Print': IconPrint,
  'Art': IconArt,
  'Figma': DesignIcons.Figma,
  'Illustration': IconIllustration,
  'Components': IconComponents,
  'Mockup': IconMockup,
  'Palette': IconPalette,
  'Image': DesignIcons.Image,
  'Photo': IconPhoto,
  'Video': DesignIcons.Video,
  'Audio': DesignIcons.Audio,
  'Camera': IconCamera,
  'AI': DesignIcons.AI,
  'Code': DesignIcons.Code,
  'Developer': DesignIcons.Developer,
  'Web': DesignIcons.Web,
  'Mobile': DesignIcons.Mobile,
  'Plugin': DesignIcons.Plugin,
  'Data': DesignIcons.Data,
  'Analytics': DesignIcons.Analytics,
  'Visualization': DesignIcons.Visualization || IconDigital,
  'GameUI': IconGameUI,
  'Metaverse': IconMetaverse,
  'Digital': IconDigital,
  'System': IconSystem,
  'Ecommerce': DesignIcons.Ecommerce,
  'Store': IconStore,
  'Marketing': IconMarketing,
  'Platform': IconPlatform,
  'LiveStreaming': IconLiveStreaming,
  'Banner': IconBanner,
  'Package': IconPackage,
  'Layout': IconLayout,
  'Specs': DesignIcons.Specs,
  'CAD': IconCAD,
  'Furniture': IconFurniture,
  'Texture': IconTexture,
  'Lighting': IconLighting,
  'Project': IconProject,
  'VR': IconVR,
  'Tool': IconTool,
  'Tools': IconTools,
  'Tutorial': DesignIcons.Tutorial,
  'Learn': DesignIcons.Learn,
  'Blog': DesignIcons.Blog,
  'Community': DesignIcons.Community,
  'Book': DesignIcons.Book,
  'Education': IconEducation,
  'Resource': DesignIcons.Resource,
  'CarUI': IconCarUI,
  'DesignTeam': IconDesignTeam,
  'AIDesign': IconAIDesign,
  'OtherContent': IconOtherContent,
  'Learning': IconLearning,
  'designTeam': IconDesignTeam,
  'carUI': IconCarUI,
  
  // ============ 兼容性映射（Heroicons/其他风格名称） ============
  'academic-cap': IconEducation,
  'briefcase': IconTools,
  'globe-alt': DesignIcons.Web,
  'shopping-cart': DesignIcons.Ecommerce,
  'music': DesignIcons.Audio,
  'Flag01': IconTools,  // Untitled UI 图标名称兼容
  
  // 默认图标
  'default': IconTool
};

export default iconMap;
